"use client";
import { useEffect, useState } from "react";
import { AdminHeader } from "../layout";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { toast } from "sonner";
const ACK="Thank you for reaching out. We have received your query and our team will get back to you soon.";
const RESOLVED="Your query has been resolved. If you are not satisfied, please reach out to us again.";
export default function MessagesPage(){const[messages,setMessages]=useState<any[]>([]);const[selected,setSelected]=useState<any>(null);const load=()=>fetch("/api/admin/communications").then(r=>r.json()).then(x=>setMessages(x.messages||[]));useEffect(()=>{void load()},[]);const act=async(status:string,reply:string)=>{const r=await fetch("/api/admin/communications",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"message",id:selected.id,status,reply})});if(!r.ok){toast.error("This action is no longer available.");return}toast.success(status==="resolved"?"Query resolved and customer notified.":"Acknowledgement sent.");setSelected(null);load()};return <div><AdminHeader title="Messages" subtitle="Manage customer contact enquiries and replies"/><div className="glass rounded-3xl p-6 overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead><tr className="border-b text-xs uppercase text-slate-400"><th className="pb-3">Name</th><th className="pb-3">Query</th><th className="pb-3">Type</th><th className="pb-3">Status</th><th className="pb-3 text-right">Action</th></tr></thead><tbody className="divide-y">{messages.map(m=><tr key={m.id}><td className="py-4 font-semibold">{m.name}</td><td className="max-w-sm py-4 text-slate-600">{m.message}</td><td className="py-4 text-primary">{m.topic}</td><td className="py-4 capitalize text-slate-500">{m.status}</td><td className="py-4 text-right"><Button size="sm" variant="outline" className="rounded-full" onClick={()=>setSelected(m)}>Manage</Button></td></tr>)}</tbody></table>{!messages.length&&<p className="py-8 text-center text-sm text-slate-500">No contact messages yet.</p>}</div><Dialog open={!!selected} onOpenChange={open=>!open&&setSelected(null)}><DialogContent className="glass-strong"><DialogHeader><DialogTitle>Contact enquiry</DialogTitle></DialogHeader>{selected&&<div className="space-y-3 text-sm"><div className="grid grid-cols-2 gap-3"><p><span className="text-slate-400">Name</span><br/>{selected.name}</p><p><span className="text-slate-400">Email</span><br/>{selected.email}</p><p><span className="text-slate-400">Phone</span><br/>{selected.phone||"-"}</p><p><span className="text-slate-400">Type</span><br/>{selected.topic}</p></div><div className="rounded-xl bg-white/60 p-4"><span className="text-slate-400">Query</span><p className="mt-1 whitespace-pre-wrap">{selected.message}</p></div><div className="flex justify-end gap-2 pt-3">{selected.status==="pending"&&<Button variant="outline" className="rounded-full" onClick={()=>act("acknowledged",ACK)}>Acknowledge</Button>}{selected.status==="acknowledged"&&<Button className="rounded-full" onClick={()=>act("resolved",RESOLVED)}>Resolved</Button>}{selected.status==="resolved"&&<span className="rounded-full bg-emerald-100 px-4 py-2 text-xs font-semibold text-emerald-700">Resolved</span>}</div></div>}</DialogContent></Dialog></div>}
