import { NextResponse } from "next/server";
import { createServiceClient } from "@/lib/supabase/server";

const img = (id: string, w = 900) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&q=80`;

const CATEGORIES = [
  { name: "Men", slug: "men", description: "Statement timepieces built for the modern man.", image: img("1522312346375-d1a52e2b99b3"), sort_order: 1 },
  { name: "Women", slug: "women", description: "Elegant, graceful watches made to adorn.", image: img("1519681393784-d120267933ba"), sort_order: 2 },
  { name: "Kids", slug: "kids", description: "Playful, durable watches for young explorers.", image: img("1539874754764-5a96559165b0"), sort_order: 3 },
  { name: "Premium", slug: "premium", description: "Exclusive Swiss & automatic masterpieces.", image: img("1547996160-81dfa63595aa"), sort_order: 4 },
  { name: "Smart Watches", slug: "smart-watches", description: "Stay connected with the latest smart tech.", image: img("1605100804763-247f67b3557e"), sort_order: 5 },
  { name: "Couple Watches", slug: "couple-watches", description: "Matching pairs for two hearts in sync.", image: img("1511499767150-a48a237f0083"), sort_order: 6 },
];

const PRODUCTS = [
  {
    name: "Sovereign Royal Black",
    description: "The Royal Black is our flagship dress watch - a midnight-black dial wrapped in a brushed stainless steel case with a sapphire crystal and exhibition caseback. Powered by a Swiss automatic movement with 41-hour power reserve.",
    short_description: "Flagship automatic dress watch with a midnight-black dial.",
    images: [img("1522312346375-d1a52e2b99b3"), img("1523275335684-37898b6baf30"), img("1587836374828-4dbafa94cf0e")],
    price: 84500,
    sale_price: 75900,
    sku: "SV-RB-001",
    stock: 12,
    low_stock_threshold: 5,
    categorySlug: "men",
    tags: ["automatic", "dress", "sapphire"],
    collections: ["best-seller", "featured"],
    movement: "Swiss Automatic (41h reserve)",
    case_material: "316L Stainless Steel",
    strap_material: "Italian Leather",
    case_size: "41mm",
    dial_color: "Midnight Black",
    water_resistance: "5 ATM",
    gender: "Men",
    warranty: "24-month international warranty",
    status: "active",
    featured: true,
  },
  {
    name: "Classic Silver Edition",
    description: "An icon of restraint. The Classic Silver Edition pairs a sunburst silver dial with polished steel indices and a slim 38mm profile.",
    short_description: "Timeless silver dial, slim 38mm steel case.",
    images: [img("1523275335684-37898b6baf30"), img("1524805444758-089113d48a6d"), img("1523170335258-f5ed11844a49")],
    price: 42900,
    sku: "SV-CS-002",
    stock: 8,
    low_stock_threshold: 3,
    categorySlug: "men",
    tags: ["quartz", "minimal", "daily"],
    collections: ["new-arrival"],
    movement: "Japanese Quartz",
    case_material: "Brushed Stainless Steel",
    strap_material: "Stainless Steel Mesh",
    case_size: "38mm",
    dial_color: "Sunburst Silver",
    water_resistance: "3 ATM",
    gender: "Unisex",
    warranty: "12-month international warranty",
    status: "active",
    featured: false,
  },
  {
    name: "Aurora Rose Gold",
    description: "Delicate yet commanding, the Aurora wraps a mother-of-pearl dial in warm rose gold plating.",
    short_description: "Mother-of-pearl dial in warm rose gold.",
    images: [img("1519681393784-d120267933ba"), img("1510017803434-a899398421b3"), img("1526045431048-f857369baa09")],
    price: 56800,
    sale_price: 48900,
    sku: "SV-AR-003",
    stock: 15,
    categorySlug: "women",
    tags: ["rose-gold", "mother-of-pearl", "elegant"],
    collections: ["new-arrival", "featured"],
    movement: "Swiss Quartz",
    case_material: "Rose Gold Plated Steel",
    strap_material: "Rose Gold Mesh",
    case_size: "32mm",
    dial_color: "Mother-of-Pearl",
    water_resistance: "3 ATM",
    gender: "Women",
    warranty: "12-month international warranty",
    status: "active",
    featured: true,
  },
  {
    name: "Celeste Diamond Accent",
    description: "The Celeste sparkles with a bezel of hand-set crystal accents around a champagne dial.",
    short_description: "Champagne dial with hand-set crystal bezel.",
    images: [img("1510017803434-a899398421b3"), img("1511499767150-a48a237f0083"), img("1523170335258-f5ed11844a49")],
    price: 72900,
    sku: "SV-CL-004",
    stock: 6,
    low_stock_threshold: 2,
    categorySlug: "women",
    tags: ["crystal", "champagne", "gift"],
    collections: ["latest-edition"],
    movement: "Swiss Quartz",
    case_material: "Silver Plated Steel",
    strap_material: "Satin Finish Steel",
    case_size: "30mm",
    dial_color: "Champagne",
    water_resistance: "3 ATM",
    gender: "Women",
    warranty: "12-month international warranty",
    status: "active",
    featured: false,
  },
  {
    name: "Junior Explorer",
    description: "Rugged, colorful, and kid-proof with shock-resistant case.",
    short_description: "Shock-resistant kids watch for big adventures.",
    images: [img("1539874754764-5a96559165b0"), img("1524592094714-0f0654e20314")],
    price: 11900,
    sale_price: 9900,
    sku: "SV-JE-005",
    stock: 30,
    categorySlug: "kids",
    tags: ["kids", "silicone", "durable"],
    collections: ["new-arrival"],
    movement: "Japanese Quartz",
    case_material: "Shock-Resistant Resin",
    strap_material: "Silicone",
    case_size: "28mm",
    dial_color: "Ocean Blue",
    water_resistance: "5 ATM",
    gender: "Kids",
    warranty: "12-month warranty",
    status: "active",
    featured: false,
  },
  {
    name: "Sovereign Gold Masterpiece",
    description: "The crown jewel of our collection. An 18k gold-plated case, sapphire crystal, and hand-finished Swiss automatic movement.",
    short_description: "Limited edition 18k gold-plated Swiss automatic.",
    images: [img("1547996160-81dfa63595aa"), img("1523170335258-f5ed11844a49"), img("1526947425960-945c6e72858f")],
    price: 345000,
    sale_price: 299000,
    sku: "SV-SG-007",
    stock: 3,
    low_stock_threshold: 2,
    categorySlug: "premium",
    tags: ["gold", "limited", "swiss"],
    collections: ["premium", "latest-edition", "featured"],
    movement: "Swiss Automatic, 21 Jewels",
    case_material: "18k Gold Plated",
    strap_material: "Crocodile Leather",
    case_size: "42mm",
    dial_color: "Ivory",
    water_resistance: "5 ATM",
    gender: "Men",
    warranty: "36-month international warranty",
    status: "active",
    featured: true,
  },
  {
    name: "Heritage Chronograph",
    description: "A tribute to motorsport. Three sub-dials, tachymeter bezel, and a bold 44mm case.",
    short_description: "Motorsport-inspired chronograph, 44mm.",
    images: [img("1524805444758-089113d48a6d"), img("1522312346375-d1a52e2b99b3")],
    price: 96500,
    sale_price: 85900,
    sku: "SV-HC-008",
    stock: 9,
    low_stock_threshold: 3,
    categorySlug: "men",
    tags: ["chronograph", "motorsport"],
    collections: ["best-seller", "premium"],
    movement: "Automatic Chronograph",
    case_material: "Brushed & Polished Steel",
    strap_material: "Leather",
    case_size: "44mm",
    dial_color: "Sunburst Black",
    water_resistance: "10 ATM",
    gender: "Men",
    warranty: "24-month international warranty",
    status: "active",
    featured: true,
  },
  {
    name: "Pulse Pro Smart Watch",
    description: "AMOLED display, GPS, heart-rate & SpO2 monitoring, 14-day battery life, IP68 water resistance.",
    short_description: "AMOLED smart watch with GPS & health tracking.",
    images: [img("1605100804763-247f67b3557e"), img("1526947425960-945c6e72858f")],
    price: 24900,
    sale_price: 19900,
    sku: "SV-PP-009",
    stock: 40,
    categorySlug: "smart-watches",
    tags: ["smart", "gps", "health"],
    collections: ["new-arrival", "best-seller"],
    movement: "Smart (AMOLED)",
    case_material: "Aluminium Alloy",
    strap_material: "Silicone",
    case_size: "46mm",
    dial_color: "Always-on AMOLED",
    water_resistance: "IP68 / 5 ATM",
    gender: "Unisex",
    warranty: "12-month warranty",
    status: "active",
    featured: true,
  },
  {
    name: "Duet His & Hers Pair",
    description: "Two watches, one heartbeat. Matched pair with engraved casebacks.",
    short_description: "Matched pair with engraved casebacks.",
    images: [img("1511499767150-a48a237f0083"), img("1519681393784-d120267933ba")],
    price: 148000,
    sale_price: 129000,
    sku: "SV-DU-011",
    stock: 7,
    low_stock_threshold: 3,
    categorySlug: "couple-watches",
    tags: ["couple", "gift", "set"],
    collections: ["featured", "best-seller"],
    movement: "Automatic (both)",
    case_material: "Steel (both)",
    strap_material: "Leather (both)",
    case_size: "41mm / 32mm",
    dial_color: "Sunburst Silver",
    water_resistance: "5 ATM",
    gender: "Unisex",
    warranty: "24-month international warranty",
    status: "active",
    featured: true,
  },
  {
    name: "Junior Ocean Sport",
    description: "A bright, easy-to-read sports watch built for school days and weekend adventures.",
    short_description: "Colorful, durable everyday watch for young explorers.",
    images: [img("1524592094714-0f0654e20314"), img("1539874754764-5a96559165b0")],
    price: 9900,
    sku: "SV-JS-006",
    stock: 24,
    categorySlug: "kids",
    tags: ["kids", "sport", "durable"],
    collections: ["new-arrival"],
    movement: "Japanese Quartz",
    case_material: "Resin",
    strap_material: "Silicone",
    case_size: "30mm",
    dial_color: "Sunshine Yellow",
    water_resistance: "5 ATM",
    gender: "Kids",
    warranty: "12-month warranty",
    status: "active",
    featured: false,
  },
  {
    name: "Imperial Automatic",
    description: "A refined automatic timepiece with a textured ivory dial and polished gold-tone details.",
    short_description: "Refined automatic watch with an ivory dial.",
    images: [img("1526947425960-945c6e72858f"), img("1547996160-81dfa63595aa")],
    price: 219000,
    sku: "SV-IA-010",
    stock: 5,
    low_stock_threshold: 2,
    categorySlug: "premium",
    tags: ["premium", "automatic", "ivory"],
    collections: ["premium", "featured"],
    movement: "Swiss Automatic",
    case_material: "316L Stainless Steel",
    strap_material: "Alligator Leather",
    case_size: "40mm",
    dial_color: "Textured Ivory",
    water_resistance: "5 ATM",
    gender: "Unisex",
    warranty: "36-month international warranty",
    status: "active",
    featured: false,
  },
  {
    name: "Pulse Mini Smart Watch",
    description: "Compact smart watch with activity tracking, notifications, sleep monitoring, and a bright touch display.",
    short_description: "Compact smart watch for everyday activity tracking.",
    images: [img("1526947425960-945c6e72858f"), img("1605100804763-247f67b3557e")],
    price: 18900,
    sale_price: 15900,
    sku: "SV-PM-013",
    stock: 35,
    categorySlug: "smart-watches",
    tags: ["smart", "fitness", "notifications"],
    collections: ["new-arrival"],
    movement: "Smart Display",
    case_material: "Aluminium Alloy",
    strap_material: "Silicone",
    case_size: "42mm",
    dial_color: "AMOLED Black",
    water_resistance: "IP68",
    gender: "Unisex",
    warranty: "12-month warranty",
    status: "active",
    featured: false,
  },
  {
    name: "Eternal Pair Classic",
    description: "A coordinated pair with clean dials, matching leather straps, and a timeless silhouette for two.",
    short_description: "Classic matching watch set for couples.",
    images: [img("1519681393784-d120267933ba"), img("1511499767150-a48a237f0083")],
    price: 119000,
    sku: "SV-EP-014",
    stock: 8,
    categorySlug: "couple-watches",
    tags: ["couple", "classic", "gift"],
    collections: ["featured", "new-arrival"],
    movement: "Japanese Quartz (both)",
    case_material: "Stainless Steel (both)",
    strap_material: "Leather (both)",
    case_size: "40mm / 32mm",
    dial_color: "Ivory / Champagne",
    water_resistance: "3 ATM",
    gender: "Unisex",
    warranty: "24-month warranty",
    status: "active",
    featured: false,
  },
  {
    name: "Stellar Night Sky",
    description: "A deep aventurine dial mimicking the cosmic night sky.",
    short_description: "Aventurine cosmic dial in gunmetal steel.",
    images: [img("1523170335258-f5ed11844a49"), img("1522312346375-d1a52e2b99b3")],
    price: 89900,
    sku: "SV-SN-012",
    stock: 10,
    categorySlug: "men",
    tags: ["aventurine", "cosmic"],
    collections: ["latest-edition", "featured"],
    movement: "Automatic Movement",
    case_material: "Gunmetal Steel",
    strap_material: "Black Mesh",
    case_size: "40mm",
    dial_color: "Aventurine Blue",
    water_resistance: "5 ATM",
    gender: "Men",
    warranty: "24-month warranty",
    status: "active",
    featured: true,
  }
];

const COUPONS = [
  { code: "WELCOME10", type: "percent", value: 10, max_discount: 5000, active: true },
  { code: "SOVEREIGN2000", type: "fixed", value: 2000, min_order: 25000, active: true },
  { code: "LUXURY15", type: "percent", value: 15, min_order: 50000, max_discount: 15000, active: true },
];

export async function POST() {
  try {
    const service = createServiceClient();

    // 1. Insert categories
    const catMap = new Map<string, string>();
    for (const cat of CATEGORIES) {
      const { data } = await service
        .from("categories")
        .upsert(cat, { onConflict: "slug" })
        .select()
        .single();
      if (data) catMap.set(data.slug, data.id);
    }

    // 2. Insert products
    for (const p of PRODUCTS) {
      const { categorySlug, ...rest } = p;
      const category_id = catMap.get(categorySlug) || null;
      await service
        .from("products")
        .upsert({ ...rest, category_id }, { onConflict: "slug" });
    }

    // 3. Insert coupons
    for (const c of COUPONS) {
      await service.from("coupons").upsert(c, { onConflict: "code" });
    }

    return NextResponse.json({ success: true, message: "Database seeded successfully" });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
