"use client";
import { useEffect, useState } from "react";
import { AdminHeader } from "../layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";

export default function Communications() {
  const [data, setData] = useState<any>({ messages: [], subscribers: [] }); const [subject, setSubject] = useState(""); const [body, setBody] = useState("");
  const load = () => fetch("/api/admin/communications").then(r => r.json()).then(setData);
  useEffect(() => { void load(); }, []);
  const update = async (payload: any) => { const r = await fetch("/api/admin/communications", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (!r.ok) throw new Error(); await load(); };
  const campaign = async () => { try { const r = await fetch("/api/admin/communications", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "campaign", subject, body }) }); const x = await r.json(); if (!r.ok) throw new Error(x.error); toast.success(`Campaign sent to ${x.sent} subscriber(s).`); setSubject(""); setBody(""); } catch (e: any) { toast.error(e.message || "Campaign failed."); } };
  return <div><AdminHeader title="Messages & Newsletter" subtitle="Manage customer enquiries and Sovereign Circle campaigns" /><div className="grid gap-6 lg:grid-cols-2"><section className="glass rounded-3xl p-6"><h2 className="mb-4 font-semibold">Contact enquiries ({data.messages.length})</h2><div className="space-y-4">{data.messages.map((m: any) => <article key={m.id} className="rounded-2xl border border-slate-200/60 p-4"><p className="font-semibold">{m.name} <span className="font-normal text-slate-500">· {m.email}</span></p><p className="text-xs text-primary">{m.topic}</p><p className="mt-2 text-sm text-slate-600">{m.message}</p><div className="mt-3 flex gap-2"><Button size="sm" className="rounded-full" onClick={() => update({ type: "message", id: m.id, status: "resolved", reply: "We have received your enquiry and will be in touch shortly." }).catch(() => toast.error("Update failed."))}>Mark resolved</Button></div></article>)}</div></section><section className="space-y-6"><div className="glass rounded-3xl p-6"><h2 className="font-semibold">Send campaign</h2><Input className="mt-4 rounded-xl" placeholder="Subject" value={subject} onChange={e => setSubject(e.target.value)} /><Textarea className="mt-3 rounded-xl" placeholder="Message" rows={6} value={body} onChange={e => setBody(e.target.value)} /><Button className="mt-3 rounded-full" onClick={campaign}>Send to active subscribers</Button></div><div className="glass rounded-3xl p-6"><h2 className="mb-4 font-semibold">Subscribers ({data.subscribers.filter((s: any) => s.status === "subscribed").length} active)</h2><div className="space-y-2 text-sm">{data.subscribers.map((s: any) => <div key={s.id} className="flex items-center justify-between"><span>{s.email}</span><Button size="sm" variant="outline" className="rounded-full" onClick={() => update({ type: "subscriber", id: s.id, status: s.status === "subscribed" ? "unsubscribed" : "subscribed" }).catch(() => toast.error("Update failed."))}>{s.status === "subscribed" ? "Unsubscribe" : "Resubscribe"}</Button></div>)}</div></div></section></div></div>;
}
